import testImg from "../assets/img/testImg.svg";
import CheckMark from "../assets/img/CheckMark.svg";
const ListingsData = [
  {
    image: <img className="testImg" src={testImg} />,
    id: "46780",
    location: "180 Niblick Rd, Paso Robles, Ca 93446",
    lotSize: "13,608 Sq. Ft. Per County",
    houseSize: "3,435 Sq. Ft. Per County",
    price: "$6,500/mo",
    public: null,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "57478",
    location: "2900 Vineyard Dr, Templeton, Ca 93465",
    lotSize: "9,355 Sq. Ft. Per County",
    houseSize: "3,435 Sq. Ft. Per County",
    price: "$5,500/mo",
    public: <img className="checkMark" src={CheckMark} alt="CheckMark" />,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "47474",
    location: "206 Alexa Ct, Paso Robles, Ca 93446",
    lotSize: "8,252 Sq. Ft. Per County",
    houseSize: "2,355 Sq. Ft. Per County",
    price: "$ 5,700 / mo",
    public: null,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "67926",
    location: "9100 Morro Rd, Atascadero, Ca 93422",
    lotSize: "12,498 Sq. Ft. Per County",
    houseSize: "2,965 Sq. Ft. Per County",
    price: "$ 6,000 / mo",
    public: <img className="checkMark" src={CheckMark} alt="CheckMark" />,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "13425",
    location: "2850 El Pomar Dr, Templeton, Ca 93465",
    lotSize: "15,464 Sq. Ft. Per County",
    houseSize: "4,754 Sq. Ft. Per County",
    price: "$ 5,200 / mo",
    public: <img className="checkMark" src={CheckMark} alt="CheckMark" />,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "24235",
    location: "1800 El Camino Real, Atascadero, Ca 93422",
    lotSize: "11,937 Sq. Ft. Per County",
    houseSize: "3,608 Sq. Ft. Per County",
    price: "$ 4,700 / mo",
    public: null,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "46720",
    location: "180 Niblick Rd, Paso Robles, Ca 93446",
    lotSize: "13,608 Sq. Ft. Per County",
    houseSize: "3,435 Sq. Ft. Per County",
    price: "$6,500/mo",
    public: <img className="checkMark" src={CheckMark} alt="CheckMark" />,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "09432",
    location: "180 Niblick Rd, Paso Robles, Ca 93446",
    lotSize: "10,428 Sq. Ft. Per County",
    houseSize: "4,461 Sq. Ft. Per County",
    price: "$ 7,900 / mo",
    public: <img className="checkMark" src={CheckMark} alt="CheckMark" />,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "07466",
    location: "2900 Vineyard Dr, Templeton, Ca 93465",
    lotSize: "5,358 Sq. Ft. Per County",
    houseSize: "2,156 Sq. Ft. Per County",
    price: "$ 5,900 / mo",
    public: <img className="checkMark" src={CheckMark} alt="CheckMark" />,
  },
  {
    image: <img className="testImg" src={testImg} alt="CheckMark" />,
    id: "32441",
    location: "206 Alexa Ct, Paso Robles, Ca 93446",
    lotSize: "9,026 Sq. Ft. Per County",
    houseSize: "2,247 Sq. Ft. Per County",
    price: "$ 4,500 / mo",
    public: null,
  },
];

export default ListingsData;
